#ifndef __FACTORIES_INCLUDED__
#define __FACTORIES_INCLUDED__

#include <flexitask/Factory.hpp>

/* BEGIN include directories */
/* END */

namespace fibonacci
{

/** @brief Factories generated by the bulk script. */
extern flexitask::Factory factories[4];

} /* namespace fibonacci */

#endif // __FACTORIES_INCLUDED__