#ifndef IPLIB_CMDQ_DEFS_H_INCLUDED
#define IPLIB_CMDQ_DEFS_H_INCLUDED

#define CMDQ_OFFSET_REQ 0x00u
#define CMDQ_OFFSET_REQDONE 0x04u
#define CMDQ_OFFSET_LENGTH 0x08u

#endif /* IPLIB_CMDQ_DEFS_H_INCLUDED */
