#ifndef __FACTORIES_INCLUDED__
#define __FACTORIES_INCLUDED__

#include <hardcilk/Factory.hpp>

/* BEGIN include directories */
/* END */

namespace paper_exp3
{

/** @brief Factories generated by the bulk script. */
extern hardcilk::Factory factories[1];

} /* namespace paper_exp3 */

#endif // __FACTORIES_INCLUDED__