#ifndef __FACTORIES_INCLUDED__
#define __FACTORIES_INCLUDED__

#include <flexitask/Factory.hpp>

/* BEGIN include files */
/* END */

namespace paper_exp_dae_0
{

/** @brief Factories generated by the bulk script. */
extern flexitask::Factory factories[4];

} /* namespace paper_exp_dae_0 */

#endif // __FACTORIES_INCLUDED__